# Generated by Django 3.2.7 on 2021-09-28 23:18

import bundle.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('papers', djongo.models.fields.ArrayField(model_container=bundle.models.Paper)),
            ],
        ),
    ]
