# Generated by Django 3.2.7 on 2021-09-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
