# Generated by Django 3.2.7 on 2021-09-28 23:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('nickname', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
