# Generated by Django 3.2.7 on 2021-09-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0002_bundle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='price_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
