# Generated by Django 3.2.7 on 2021-09-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0002_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
