# Generated by Django 3.2.7 on 2021-10-24 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0003_bundle_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bundle_type_images')),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='bundle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bundle.bundletype'),
        ),
    ]
