# Generated by Django 3.2.7 on 2021-10-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0004_auto_20211024_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='bundle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bundle.bundletype'),
        ),
    ]
