# Generated by Django 3.2.7 on 2021-10-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0005_alter_bundle_bundle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='slug',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bundletype',
            name='slug',
            field=models.CharField(default='', max_length=120),
        ),
    ]
