# Generated by Django 3.2.7 on 2021-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0006_auto_20211025_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bundletype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bundletype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
